name: ESLint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
    types: [opened, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          npm install
          npm install -g eslint
          npm install @babel/eslint-parser --save-dev
      - name: Run ESLint
        working-directory: ./frontend
        run: eslint "src/**/*.{js,jsx,ts,tsx,md,json}" --max-warnings 0
